---
abstract: 'Plugin for geocoding and reverse geocoding features!'
author:
  - 'Rohit Deshmukh <raigad1630@gmail.com>'
build_requires:
  Test::More: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-GeoCoder
no_index:
  directory:
    - t
    - inc
requires:
  Geo::Coder::Google: 0
  Mojolicious: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/raigad/mojolicious-plugin-geocoder/issues
  homepage: http://search.cpan.org/~raigad/mojolicious-plugin-geocoder/
  repository: git://github.com/raigad/mojolicious-plugin-geocoder.git
version: 0.05
